# Generated by Django 5.0.3 on 2024-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
